.PHONY: clean All

All:
	@echo "----------Building project:[ keypad_i - Debug ]----------"
	@cd "keypad_i" && "$(MAKE)" -f  "keypad_i.mk"
clean:
	@echo "----------Cleaning project:[ keypad_i - Debug ]----------"
	@cd "keypad_i" && "$(MAKE)" -f  "keypad_i.mk" clean
